# Generated by Django 5.1.1 on 2024-10-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_attraction_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'verbose_name': 'Аттракцион', 'verbose_name_plural': 'Аттракционы'},
        ),
        migrations.AddField(
            model_name='attraction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attractions/', verbose_name='Фото'),
        ),
    ]
